# Generated by Django 2.1.4 on 2018-12-17 22:01

from django.db import migrations, IntegrityError


def add_forbes_feed(apps, schema_editor):
    """Adding Forbes Real Time feed to have some initial data."""
    Publisher = apps.get_model("content", "Publisher")
    Feed = apps.get_model("feeds", "Feed")

    forbes = Publisher.objects.get(domain="https://www.forbes.com")

    try:
        Feed.objects.create(
            publisher=forbes,
            title="Forbes Real Time",
            uri="https://www.forbes.com/real-time/feed2/",
        )
    except IntegrityError:
        # Forbes Real Time feed already exists in db
        pass


def downgrade(apps, schema_editor):
    """
    Not implemented since we actually don't want to delete the initial feed.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0002_auto_20181217_2148"),
        ("content", "0002_auto_20181217_2157"),
    ]

    operations = [migrations.RunPython(add_forbes_feed, downgrade)]
