# Generated by Django 2.1.4 on 2018-12-17 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uri", models.URLField(unique=True)),
                ("title", models.TextField()),
                ("content_source", models.TextField()),
                ("content_clean", models.TextField(blank=True, default="")),
                ("published_ts", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("parsing_started", "Parsing Started"),
                            ("parsing_finished", "Parsing Finished"),
                            ("parsing_error", "Parsing Error"),
                        ],
                        default="created",
                        max_length=30,
                    ),
                ),
            ],
            options={"ordering": ("-published_ts",)},
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("domain", models.URLField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="content.Publisher",
            ),
        ),
    ]
