# Generated by Django 2.1.4 on 2018-12-17 21:57

from django.db import migrations, IntegrityError


def add_forbes(apps, schema_editor):
    """Adding Forbes to the list of publishers to have some initial data."""
    Publisher = apps.get_model("content", "Publisher")

    try:
        Publisher.objects.create(name="Forbes", domain="https://www.forbes.com")
    except IntegrityError:
        # Forbes already exists in db
        pass


def downgrade(apps, schema_editor):
    """
    Not implemented since we actually don't want to delete the initial publisher.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [("content", "0001_initial")]

    operations = [migrations.RunPython(add_forbes, downgrade)]
