# Generated by Django 2.1.4 on 2018-12-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("content", "0003_auto_20181217_2326")]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("content_fetched", "Content Fetched"),
                    ("response_error", "Response Error"),
                ],
                default="created",
                max_length=30,
            ),
        )
    ]
