# Generated by Django 2.1.4 on 2018-12-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("content", "0005_auto_20181218_1726")]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="sentiment_score",
            field=models.FloatField(default=0),
        )
    ]
